# Render Configuration for SPA Routing
services:
  - type: static_site
    name: Frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    rootDir: Frontend/
    publishPath: Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        status: 200
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable